### ISSUE TITLE
composer/composer:master image is out of date

### ISSUE THREAD

**Issue by sjparkinson** [RobLoach/docker-composer#25]
The master image is version `1.0-dev (66acee7feb51d4b30e8983c703bf07ce1d06883e) 2015-09-12 22:04:37`.

The latest composer version is `1.0-dev (a54f84f05f915c6d42bed94de0cdcb4406a4707b) 2015-10-13 13:09:04`.

Among other changes it's missing out on the new `--classmap-authoritative` option for the install command.

It'd be great to automate updating of the master image when the composer project is updated.

**Comment by pmoust** [comment]
@sjparkinson triggered an automated build on docker hub. In a few minutes the images will be updated.

**Comment by sjparkinson** [comment]
@pmoust thanks, it's all up to date now :+1:.
