### ISSUE TITLE
Add support for php7

### ISSUE THREAD

**Issue by agiuliano** [RobLoach/docker-composer#29]
Php 7 is going to be released, why not to add a branch with php7 under the hood?

**Comment by RobLoach** [comment]
https://hub.docker.com/r/library/php/

Looks like targeting `7-cli` will bring in PHP 7.0.0-RC8 currently. Sounds like a great plan.

**Comment by agiuliano** [comment]
@RobLoach is it normal that if I enter in the downloaded composer/composer:php7 and I type `php --version` it says `PHP 5.6.15 (cli)`?

**Comment by RobLoach** [comment]
@agiuliano It's because `php7` uses `composer/composer:base`, which is currently tagged as using PHP 5.6 :wink: . We'll need a `composer/composer:php7-base`, or something.

**Comment by agiuliano** [comment]
but in composer/composer:base I see that php-7 is required in the php7 branch (https://github.com/RobLoach/docker-composer/blob/php7/base/Dockerfile)

**Comment by RobLoach** [comment]
True, but `composer/composer:base` is tagged on Docker Hub with php 5.6. We'll need to modify the branch to use a different base.

**Comment by agiuliano** [comment]
you're right, do you already tagged the `php7-base` on dockerhub to the `php7` branch?

**Comment by RobLoach** [comment]
`composer/composer:php7` should be up by now.

**Comment by RobLoach** [comment]
Now that PHP 7.0.5 is out, and considered stable. I'm proposing we switch `composer/composer:base` to target `php:cli`.
