### ISSUE TITLE
run `laravel new blog` is failed

### ISSUE THREAD

**Issue by SydOps** [RobLoach/docker-composer#57]
For the install instruction, I run below command to create a new project.

```
$ cat /usr/local/bin/composer
#!/bin/sh
export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
echo "Current working directory: '"$(pwd)"'"
docker run --rm -v $(pwd):/app -v ~/.ssh:/root/.ssh composer/composer $@

$ composer
Current working directory: '/Users/bill/composer'
   ______
  / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
                    /_/
Composer version 1.0.0 2016-04-05 13:27:25
```
### problem 1

If I run `composer global require "laravel/installer"`, the command runs well, but there is no new folders generated. 

So I have to manually created a `composer.json` file, and this time I got all vendor folders. 

```
$ cat composer.json
{
    "require": {
        "laravel/installer": ">=1.3.3"
    }
}

$ composer install
```
### problem 2

I need create a new project, I run below command: 

```
$ vendor/bin/laravel new blog
...
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Generating autoload files
Application ready! Build something amazing.
```

I found the `APP Key` is not automatically generated, if I run the command manually:

```
$ php artisan key:generate

Warning: require(/Users/bill/composer/blog/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /Users/bill/composer/blog/bootstrap/autoload.php on line 17

Fatal error: require(): Failed opening required '/Users/bill/composer/blog/bootstrap/../vendor/autoload.php' (include_path='.:') in /Users/bill/composer/blog/bootstrap/autoload.php on line 17
```

then I run with `composer create-project --prefer-dist laravel/laravel blog`, this time everything works fine. 

```
$ composer create-project --prefer-dist laravel/laravel blog
...
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Writing lock file
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
```

**Comment by RobLoach** [comment]
Nice job on the `composer` script. @renatomefidf brought up some good permissions tips in https://github.com/RobLoach/docker-composer/issues/35 . Would end up adding `--user $(id -u)` to the command.

What is APP_Key in this case?

**Comment by SydOps** [comment]
@RobLoach 

I follow the instruction in [Laravel installation](https://laravel.com/docs/5.2#installation)

**Comment by SydOps** [comment]
Maybe I knew the reason for the first problem.
```
$ composer global config bin-dir --absolute
Current working directory: '/Users/bill/study/bitbucket.org/homestay/yii2'
Changed current directory to /composer
/composer/vendor/bin
```
With global option, the package were installed to container's folder `/composer/vendor/bin`, but our container only exposes `/app` folder. That's why I didn't see anything after I run `composer global require "laravel/installer"`

**Comment by SydOps** [comment]
@RobLoach Seems you have added the global path into `Dockerfile` at 

https://github.com/RobLoach/docker-composer/blob/585d9053c7a288385a861dd8cf79886710bf21f4/base/alpine/Dockerfile#L43

Can you explain how to make it work with `composer global require "laravel/installer"`

**Comment by SydOps** [comment]
Since I can't build the base image directly (reported in #66), here is my work around to fix this issue.

```
$ cat Dockerfile
FROM composer/composer
WORKDIR /composer

$ cat /usr/local/bin/composer
#!/bin/sh

export PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
echo "Current working directory: '"$(pwd)"'"
docker run --rm -v $(pwd):/composer -v ~/.ssh:/root/.ssh composer $@
```

So I change the `WORKDIR` to /composer in Dockerfile and composer script.

Now I am fine to run composer with `global` option.

**Comment by RobLoach** [comment]
@SydOps Thanks for looking into this... Updated the installer hash at https://github.com/RobLoach/docker-composer/pull/67 , mind reviewing?
