### ISSUE TITLE
Official Repo

### ISSUE THREAD

**Issue by sylus** [RobLoach/docker-composer#62]
I was reading over: https://github.com/docker-library/official-images

and just wondering if over the next few weeks / months we were going to try to make this the official repo for composer? If the upstream folks are cool with that?

I think we just need to add a customized update.sh + generate-stackbrew-library.sh script which I am happy to start taking a look at, but wanted to check in first. ^_^

**Comment by RobLoach** [comment]
Started the conversation around this over at https://github.com/RobLoach/docker-composer/issues/40 . I'll add the link you posted over there :+1: .
