### ISSUE TITLE
Switch folder structure from x.x.x to x.x 

### ISSUE THREAD

**Issue by sylus** [RobLoach/docker-composer#74]
I noticed most (not sure if all) of the official docker images are using a simplified folder structure. They only take the major.minor version and map that to a folder name. When the major.minor.patch is updated that gets reflected in the dockerfile but if the major.minor didn't change the folder name wouldn't.

Is this something we wanted to take a look at? Here are some examples showing all the tags still existing but folder structure a bit simplified in the repo:

Solr

https://github.com/docker-solr/docker-solr
https://hub.docker.com/r/library/solr/tags/

Postgres

https://github.com/docker-library/postgres
https://hub.docker.com/r/library/postgres/tags/

Node

https://github.com/nodejs/docker-node
https://hub.docker.com/r/library/postgres/tags/

I for sure might be missing something but thought would start discussion :)

**Comment by pirog** [comment]
@sylus you at the drupalcon by any chance?

**Comment by RobLoach** [comment]
Suggesting dropping the PATCH support? Just doing the latest patch from any MAJOR.MINOR pair?

**Comment by sylus** [comment]
@pirog sorry I wasn't able to make it to DrupalCon this year! Feel free to reach out to me however through email / slack and what not ^_^

@RobLoach yeah that is what I am thinking, I'll try to get a P.R. going within a couple of days. ^_^

**Comment by sylus** [comment]
Nevermind already done, thanks you so much! I'll add a small pr to update the update.sh script since now using x.x not x.x.x
