### ISSUE TITLE
[bug] PHP7 tag installs PHP 5.x.x

### ISSUE THREAD

**Issue by andrewmclagan** [RobLoach/docker-composer#78]
There are allot of down stream providers that depend on this repository AKA PHPUnit:

https://github.com/JulienBreux/phpunit-docker/issues/25

Please let us know if there are intentions to fix this issue or we will have to migrate to another image.

thanks :-)

**Comment by RobLoach** [comment]
The convention is latest and greatest by default. Just remove `php7` from the tag :wink: .

**Comment by andrewmclagan** [comment]
oh really ...

**Comment by RobLoach** [comment]
Think we should add the `php7` tags to avoid this issue in the future?

**Comment by andrewmclagan** [comment]
yeah perhaps, although not sure its a huge issue?

**Comment by RobLoach** [comment]
Just added it, undocumented, should take a bit to build.

**Comment by andrewmclagan** [comment]
:-) thanks !
