### ISSUE TITLE
Alpine Build Broken

### ISSUE THREAD

**Issue by RobLoach** [RobLoach/docker-composer#81]
```
ERROR: unsatisfiable constraints:
  php-pear (missing):
    required by: world[php-pear]
```

**Comment by sylus** [comment]
Think just need to remove php-pear now? odd worked before.

**Comment by sylus** [comment]
Seems to only be in edge?

https://pkgs.alpinelinux.org/packages?name=php7-pear&branch=&repo=&arch=&maintainer=

**Comment by sylus** [comment]
All fixed up now.

**Comment by RobLoach** [comment]
Nice job! :+1:
