### ISSUE TITLE
Too Many Deps

### ISSUE THREAD

**Issue by rawkode** [RobLoach/docker-composer#97]
Why does the base composer images install so many php extensions and system deps? Are these really all required?

If they are, please let me know.

If they're there to cover general use-cases, I'll submit a PR to provide this in a more sophistiated manner.

**Comment by RobLoach** [comment]
Majority of them are dependencies of Composer itself, or the most common packages from Packagist. Would love any ideas or improvements you have to it. Can run into dependency hell.

**Comment by Richtermeister** [comment]
I think ideally the composer images should only include extensions/system deps required by composer, and we should advocate installing everything with the `--ignore-platform-reqs` flag enabled, possibly `--no-scripts` as well. This container should really just be used for obtain the vendor files, not create a runtime environment for the application.

**Comment by alcohol** [comment]
Using the `--ignore-platform-reqs` flag is the preferred approach in my humble opinion.

If however users use the container for more than just the build step (also run tests etc), then extra extensions might be a necessity. In that case it is probably best to advise users to extend the composer image with their own Dockerfile, in which they can install the necessary extensions.

That way you can provide a lean and slim base image.
