### ISSUE TITLE
How to add extension php-intl

### ISSUE THREAD

**Issue by iamthom** [RobLoach/docker-composer#98]
How can I add php extension intl to composer? I got this error `requires ext-intl * -> the requested PHP extension intl is missing from your system.`

**Comment by Richtermeister** [comment]
Ideally you don't try to add those extensions to this container, instead run composer install with the `--ignore-platform-reqs` flag.

**Comment by iamthom** [comment]
@Richtermeister Thank you! You rocks. It works. I'm such a dumb to not know this flag -_-

**Comment by Richtermeister** [comment]
Awesome, glad I could help.
